# Generated by Django 4.0 on 2023-06-26 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('created_by', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('created_by', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='created_by',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='geo_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='main_photo',
            field=models.ImageField(null=True, upload_to='properties'),
        ),
        migrations.AddField(
            model_name='property',
            name='occupied_units',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_units',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.county'),
        ),
        migrations.AddField(
            model_name='property',
            name='propertytype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.propertytype'),
        ),
    ]
